global:
  scrape_interval: 15s # How often to grab metrics

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['app:80'] # 'app' matches the service name in docker-compose
